---
apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
 labels:
  color: green
spec:
 containers:
 - name: nginx-container
   image: websurf500/mynginx
   ports:
   - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-svc
spec:
 selector:
  color: green
 type: LoadBalancer
 ports:
 - port: 80
   targetPort: 80
...